version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: fastai-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      # Default DB, though we use 'fastAIstackdb' via configuration
      POSTGRES_DB: fastaistackdb
    ports:
      - "15432:5432"
    volumes:
      - fastai_postgres_data:/var/lib/postgresql/data

volumes:
  fastai_postgres_data:
