version: '3.8'

services:
  db:
    image: pgvector/pgvector:pg15
    container_name: fastai-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      # Default DB, though we use 'fastagentdb' via configuration
      POSTGRES_DB: fastagentdb
    ports:
      - "15432:5432"
    volumes:
      - fastaistack_fastai_postgres_data:/var/lib/postgresql/data

volumes:
  fastaistack_fastai_postgres_data:
    external: true
