"""add is_deleted to thoughts and schedules

Revision ID: 67351a117fcd
Revises: 043d7855986b
Create Date: 2026-03-23 14:31:25.078650

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67351a117fcd'
down_revision: Union[str, None] = '043d7855986b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedules', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_schedules_is_deleted'), 'schedules', ['is_deleted'], unique=False)
    op.add_column('thoughts', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_thoughts_is_deleted'), 'thoughts', ['is_deleted'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_thoughts_is_deleted'), table_name='thoughts')
    op.drop_column('thoughts', 'is_deleted')
    op.drop_index(op.f('ix_schedules_is_deleted'), table_name='schedules')
    op.drop_column('schedules', 'is_deleted')
    # ### end Alembic commands ###
