"""add_garden_configs_table

Revision ID: 74d0cc146cf2
Revises: fbf2e6900c74
Create Date: 2026-03-31 21:44:41.793105

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74d0cc146cf2'
down_revision: Union[str, None] = 'fbf2e6900c74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
