"""update thoughts and schedules schema

Revision ID: 8475775a750c
Revises: eb513b1a2dc8
Create Date: 2026-03-22 23:37:53.545314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8475775a750c'
down_revision: Union[str, None] = 'eb513b1a2dc8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedules', sa.Column('location', sa.String(), nullable=True))
    op.add_column('schedules', sa.Column('status', sa.String(), nullable=True))
    op.add_column('schedules', sa.Column('reminder_time', sa.DateTime(), nullable=True))
    op.add_column('schedules', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_schedules_status'), 'schedules', ['status'], unique=False)
    op.create_index(op.f('ix_schedules_user_id'), 'schedules', ['user_id'], unique=False)
    op.drop_column('schedules', 'description')
    op.alter_column('thoughts', 'content', new_column_name='original_content')
    op.add_column('thoughts', sa.Column('refined_content', sa.Text(), nullable=True))
    op.add_column('thoughts', sa.Column('tags', sa.String(), nullable=True))
    op.add_column('thoughts', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_thoughts_user_id'), 'thoughts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('thoughts', 'original_content', new_column_name='content')
    op.drop_index(op.f('ix_thoughts_user_id'), table_name='thoughts')
    op.drop_column('thoughts', 'updated_at')
    op.drop_column('thoughts', 'tags')
    op.drop_column('thoughts', 'refined_content')
    op.add_column('schedules', sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_schedules_user_id'), table_name='schedules')
    op.drop_index(op.f('ix_schedules_status'), table_name='schedules')
    op.drop_column('schedules', 'updated_at')
    op.drop_column('schedules', 'reminder_time')
    op.drop_column('schedules', 'status')
    op.drop_column('schedules', 'location')
    # ### end Alembic commands ###
