"""add thought_type and source_ids to thoughts

Revision ID: 8c3d4577f1f7
Revises: 74d0cc146cf2
Create Date: 2026-04-01 21:33:39.335797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from models.models import StringArray

# revision identifiers, used by Alembic.
revision: str = '8c3d4577f1f7'
down_revision: Union[str, None] = '74d0cc146cf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cluster_previews_id'), table_name='cluster_previews')
    op.drop_index(op.f('ix_cluster_previews_user_id'), table_name='cluster_previews')
    op.drop_table('cluster_previews')
    op.add_column('thoughts', sa.Column('source_ids', StringArray(), nullable=True))
    op.alter_column('thoughts', 'thought_type',
               existing_type=postgresql.ENUM('ATOMIC', 'THEMED', name='thoughttype'),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_column('thoughts', 'ref_atomic_ids')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thoughts', sa.Column('ref_atomic_ids', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    op.alter_column('thoughts', 'thought_type',
               existing_type=sa.String(),
               type_=postgresql.ENUM('ATOMIC', 'THEMED', name='thoughttype'),
               existing_nullable=True)
    op.drop_column('thoughts', 'source_ids')
    op.create_table('cluster_previews',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('topic_title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('preview_content', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('atomic_ids', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('cluster_previews_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('cluster_previews_pkey'))
    )
    op.create_index(op.f('ix_cluster_previews_user_id'), 'cluster_previews', ['user_id'], unique=False)
    op.create_index(op.f('ix_cluster_previews_id'), 'cluster_previews', ['id'], unique=False)
    # ### end Alembic commands ###
