"""add vector embedding to thoughts

Revision ID: b12485ac7feb
Revises: 67351a117fcd
Create Date: 2026-03-31 17:47:30.143048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'b12485ac7feb'
down_revision: Union[str, None] = '67351a117fcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thoughts', sa.Column('is_public', sa.Boolean(), nullable=True))
    op.add_column('thoughts', sa.Column('embedding', pgvector.sqlalchemy.Vector(dim=1536), nullable=True))
    op.create_index(op.f('ix_thoughts_is_public'), 'thoughts', ['is_public'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_thoughts_is_public'), table_name='thoughts')
    op.drop_column('thoughts', 'embedding')
    op.drop_column('thoughts', 'is_public')
    # ### end Alembic commands ###
