"""update embedding dimension to 2048

Revision ID: fbf2e6900c74
Revises: b12485ac7feb
Create Date: 2026-03-31 18:16:21.193793

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'fbf2e6900c74'
down_revision: Union[str, None] = 'b12485ac7feb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('thoughts', 'embedding',
               existing_type=pgvector.sqlalchemy.Vector(dim=1536),
               type_=pgvector.sqlalchemy.Vector(dim=2048),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('thoughts', 'embedding',
               existing_type=pgvector.sqlalchemy.Vector(dim=2048),
               type_=pgvector.sqlalchemy.Vector(dim=1536),
               existing_nullable=True)
    # ### end Alembic commands ###
