from .search import SEARCH_TOOLS_SCHEMA, SEARCH_REGISTRY
from .thought import THOUGHT_TOOLS_SCHEMA, THOUGHT_REGISTRY
from .schedule import SCHEDULE_TOOLS_SCHEMA, SCHEDULE_REGISTRY

# 集中注册所有物理隔离的 Skills 的执行逻辑 (供 Agent 调度器直接调用)
TOOL_REGISTRY = {}
TOOL_REGISTRY.update(SEARCH_REGISTRY)
TOOL_REGISTRY.update(THOUGHT_REGISTRY)
TOOL_REGISTRY.update(SCHEDULE_REGISTRY)

# 集中暴露所有 Skills 的 JSON Schema (供发送给大模型)
TOOLS = []
TOOLS.extend(SEARCH_TOOLS_SCHEMA)
TOOLS.extend(THOUGHT_TOOLS_SCHEMA)
TOOLS.extend(SCHEDULE_TOOLS_SCHEMA)

__all__ = ["TOOL_REGISTRY", "TOOLS"]
